"""Add index on name column

Revision ID: aede1295f0b4
Revises: 9268162e37d5
Create Date: 2025-01-08 12:49:53.197298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aede1295f0b4'
down_revision: Union[str, None] = '9268162e37d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_results_additional_info', 'results', ['additional_info'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_results_additional_info', table_name='results', postgresql_using='gin')
    # ### end Alembic commands ###
